#!/bin/sh

finish() {
    if [ -z "$1" ] || [ -z "$CYDIA" ]; then
        return
    fi
    read -r fd ver <<EOF
$CYDIA
EOF
    [ "$ver" -eq 1 ] || return
    # shellcheck disable=SC2039,SC3021
    echo "finish:$1" >&"$fd"
}

if [ "$1" = "remove" ]; then
    rm -f /var/mobile/Library/Preferences/net.cadoth.fakepass.plist
    killall -9 cfprefsd 2>/dev/null || true
    finish restart
fi
